### ISSUE TITLE
share extension doesn't keep data URL encoded images in HTML

### ISSUE THREAD

**Issue by ldenoue** [evernote/ios8-share-extension-demo#2] opened 2015-03-17 19:01 UTC
whenever I put HTML payload, the EverNote Extension seesm to remove images if their URL are like "data:image/jpeg;base64"

**Comment by everic** [comment] 2015-03-19 05:15
Hello
Thank you for reporting this issue

I've filed a ticket in our Jira system, IOSNOTE-19159
If there's an update, I'll let you know.

Thank you.

**Comment by everic** [comment] 2015-04-01 04:35
Comments from our ios tech lead:

Share extensions have a limited amount of memory. And the way the HTML is being passed back/forth between native code, WebView, back to native, etc it adds up very quickly. We're deliberately stripping data URIs to avoid memory related crashes.

So I think this is by design and will not likely to change in the near future.

**Comment by ldenoue** [comment] 2015-04-01 20:12
Good to know.
My own action extension @readerviewapp http://appsto.re/us/dgI44.i also runs out of memory sometimes when it processes long web pages.
Perhaps there's also a time limit related to how UIWebViews handle javascript execution.

Laurent

**Comment by everic** [comment] 2015-04-15 16:52
Closing as by design

**Closed by everic** 2015-04-15 16:52 UTC
